### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by wcx19911123** [sunfkny/genshin-gacha-export#6]
**问题描述**
0.已经关闭了代理
1.按照流程生成了正确的excel文件
2.但是执行窗口报错了，而且也不能按任意键退出

**系统版本**
win10 1909 操作系统版本18363.1316

**错误信息**
`设置代理...成功
开始捕获链接...成功
清除代理...成功
检查URL...Traceback (most recent call last):
  File "mitmproxy\proxy\server.py", line 121, in handle
  File "mitmproxy\proxy\modes\http_proxy.py", line 9, in __call__
  File "mitmproxy\proxy\protocol\tls.py", line 285, in __call__
  File "mitmproxy\proxy\protocol\http1.py", line 100, in __call__
  File "mitmproxy\proxy\protocol\http.py", line 204, in __call__
  File "mitmproxy\proxy\protocol\http.py", line 277, in _process_flow
  File "mitmproxy\proxy\protocol\http.py", line 222, in handle_regular_connect
  File "mitmproxy\proxy\protocol\tls.py", line 285, in __call__
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
正常
获取物品信息...物品数：74
获取卡池信息...新手祈愿 常驻祈愿 角色活动祈愿 武器活动祈愿
获取抽卡数据...新手祈愿 常驻祈愿 角色活动祈愿 武器活动祈愿
清除历史文件...
写入文件...XLS
执行完成，按任意键退出...Traceback (most recent call last):
  File "mitmproxy\proxy\server.py", line 121, in handle
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy`

**附加截图**
![屏幕截图 2021-01-25 232943](https://user-images.githubusercontent.com/5677587/105726774-65409900-5f65-11eb-8ef7-96ff2a64bd20.jpg)

**Comment by sunfkny** [comment]
和 #5 一样
用这个测试版本 https://github.com/sunfkny/genshin-gacha-export/releases/tag/v1.1.1-dev 看看
如果没问题我就合并到正式版了

**Comment by sunfkny** [comment]
https://github.com/sunfkny/genshin-gacha-export/releases/tag/v1.1.2-dev
