### ISSUE TITLE
使用工具时报错 UnicodeDecodeError: 'gbk' codec can't decode byte 0xb8 in position 36368: illegal multibyte sequence

### ISSUE THREAD

**Issue by soupedog** [sunfkny/genshin-gacha-export#62]
**问题描述**

未知，某一天启动小工具时突然无法正常工作了，异常前一两天还是正常的

**系统版本**

``Windows10 22H2(19045.2364)``

**错误信息**

```
2022-12-31 15:22:12.084 | INFO     | __main__:<module>:246 - 项目主页: https://github.com/sunfkny/genshin-gacha-export
2022-12-31 15:22:12.087 | INFO     | __main__:<module>:247 - 作者: sunfkny
2022-12-31 15:22:12.089 | INFO     | __main__:<module>:248 - 版本: v3.3.0.12101546
2022-12-31 15:22:12.097 | INFO     | updater:update:99 - 更新发布: https://github.com/sunfkny/genshin-gacha-export/releases
2022-12-31 15:22:12.099 | INFO     | updater:update:100 - Coding 制品库(国内推荐): https://sunfkny.coding.net/public-artifacts/genshin-gacha-export/releases/packages
2022-12-31 15:22:12.303 | INFO     | updater:update:136 - 当前已是最新版本
2022-12-31 15:22:12.306 | INFO     | __main__:<module>:261 - 检查配置文件中的链接
2022-12-31 15:22:12.591 | WARNING  | __main__:checkApi:212 - 链接过期
2022-12-31 15:22:12.645 | INFO     | __main__:<module>:277 - 使用剪贴板模式
2022-12-31 15:22:12.650 | INFO     | __main__:<module>:285 - 剪贴板中无链接
2022-12-31 15:22:12.653 | INFO     | __main__:<module>:304 - 云·原神日志不存在
2022-12-31 15:22:12.655 | INFO     | __main__:<module>:322 - 使用日志 C:\Users\Administrator\AppData\LocalLow\miHoYo\原 神\output_log.txt
2022-12-31 15:22:12.661 | ERROR    | __main__:<module>:373 - 日志读取模块出错: Traceback (most recent call last):
  File "main.py", line 329, in <module>
  File "pathlib.py", line 1267, in read_text
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 556483: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 332, in <module>
  File "pathlib.py", line 1267, in read_text
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb8 in position 36368: illegal multibyte sequence

2022-12-31 15:22:12.665 | INFO     | utils:pressAnyKeyToExit:20 - 执行结束，按任意键退出
```

**附加截图**

**Comment by sunfkny** [comment]
麻烦打开看一下 output_log.txt 日志文件的编码（记事本打开右下角），gbk和utf-8怎么会都解码不了呢

![image](https://user-images.githubusercontent.com/30853461/210133231-f1b10a44-b686-4426-b25e-f3fc9d3b2de8.png)

**Comment by soupedog** [comment]
![QQ截图20221231182757](https://user-images.githubusercontent.com/23355314/210133540-9984e167-7660-4508-b546-a1b7f22a38a2.jpg)

记事本打开是这样

![QQ截图20221231182823](https://user-images.githubusercontent.com/23355314/210133573-c39a76c1-94c2-44cb-b8e6-3ab15b1a1fa0.jpg)

其他工具打开是这样，我现在已经没法确定原始文件是啥格式了，或者说我看见的只是编辑器默认值





最后我试着把 ``C:\Users\Administrator\AppData\LocalLow\miHoYo\原 神\output_log.txt`` 删除后，工具提示重新抓包，然后恢复正常了
